/**
 * Araucanía map: forest and Mapuche camp to the west, the Spanish Fort Tucapel
 * to the east, December 1553 (48x44 tiles). Uppercase letters and digits are
 * markers; see ARAUCANIA_MARKER_BASE for the tile underneath each one.
 *
 * Legend:  . meadow   , quila thicket (hides you)   : path   t coihue   a araucaria   k canelo (foye)
 *          ~ stream   o stepping stones   s gravel bank   r ruka   w rewe   f campfire   m pottery
 *          p palisade   _ packed earth   h adobe wall   x tile roof   n door   * copihue   # Nahuelbuta rock
 *          u earth mound   v raised bank: hop down southward only
 */
export const ARAUCANIA_MAP = [
  't##############################################t',
  't##############################################t',
  't.t.tt..t..t.t.t.....s~~s.........t............t',
  't,.tt.tt,t..t..t.....s~~s...................tttt',
  't..............t..4..s~~s..................t..tt',
  'tt.t,t,.tttt...t.....s~~s...a,....t.t........t.t',
  'ta.tt.t.ktta.t..,....s~~sa.,a,,..t...t.t.......t',
  'tt...tt......t.....,.s~~s...............tt..t.tt',
  'tta....t.t.,tt.a....,s~~s...,,,ppppppppppppppppt',
  'tatt..,.tt.ttat......s~~s...,B,p_____________Opt',
  'ttt.ttt....tt.t..,...soos...,,,p____hhhhhhh___pt',
  't################a,..soos..,,,,p____h_____h___pt',
  'ttt..........k.##...,s~~s..,,..p__I_h__1__h___pt',
  'tt..rrrr..rrrr.##.,.,s~~s......p____h_____h___pt',
  't...rrrr..rrrr.##...,s~~s.,....p____h_____h___pt',
  'tt..rrrr..rrrr.##....s~~s..,...p____hhh_hhh___pt',
  'tt......:.*...*##a...s~~s......p______________pt',
  'tt...G..:L**5..##....s~~s......p______________pt',
  't..*....:f.....##..,.s~~s.,....p_____K______N_pt',
  't.krrr..:..w...##.,..s~~s..,..,p______________pt',
  'tk.rrr*.:...C..##..,.s~~s,..,.,p______________pt',
  't..rrr..:..*...##.,.,s~~s,.,,,.p___9__________pt',
  'ta......:....m.##...,s~~s..,A,,p______________pt',
  't.t.m...W......##....s~~s..,,,.p__J___________pt',
  't#######:########....s~~s......p________hhhhhhpt',
  'tt...t..:t.,..tt,....soos,.,...UF_______h___mhpt',
  'tt.kt...Ptktttt.:D:::soos::::E:_________h____hpt',
  'tt..t..t:..t.....,,..soos.,,.,,UH_____R____2_hpt',
  'taaa....:.,t.........s~~s......p________hm__mhpt',
  't......t:.t..,.k.....s~~s......p_xxxxxx_hhhhhhpt',
  'tkt.t...:t.....t.....s~~s.Q.,.,p_xxxxxx_______pt',
  'ta..tat.:t...tt..Y...s~~s...,a.p_hhnhhh_____7_pt',
  'tt..t...:.k.,k,......s~~s......p______________pt',
  'tttt...t:.t.ttt....V.s~~s,..,..p______________pt',
  'ttt.....:....t.a.....s~~s,.....pppppppppppuppppt',
  't..6.........k.....,.soos.a.a.............v,.,,t',
  'ttt...M.:::::::::::::soos::::::::::::::::::::::t',
  'tat.....*...k........s~~s.......,......,..,...,t',
  'ttt...S.*...att.....,s~~s.........,...,...X.T,.t',
  'tt.........k.t.....,.s~~s...................,..t',
  'tt...tt......,.t.....s~~s....,.......3.........t',
  'tt.tt..t.t.ta..t.....s~~s.........,..........,.t',
  't##############################################t',
  't##############################################t',
];

export const ARAUCANIA_MARKER_BASE: Record<string, string> = {
  '1': '_',
  '2': '_',
  '3': '.',
  '4': '.',
  '5': '.',
  '6': '.',
  '7': '_',
  '9': '_',
  A: ',',
  B: ',',
  C: '.',
  D: ':',
  E: ':',
  F: '_',
  G: '.',
  H: '_',
  I: '_',
  J: '_',
  K: '_',
  L: '.',
  M: '.',
  N: '_',
  O: '_',
  P: ':',
  Q: '.',
  R: '_',
  S: '.',
  T: '.',
  U: '_',
  V: '.',
  W: ':',
  X: '.',
  Y: '.',
};
