/**
 * Neo-Tokyo map, 2087: a canal off the Sumida River, a plaza with Hachikō's
 * statue and a small Shinto shrine, neon streets, a maglev depot and the
 * Chronos Corp tower (48x40 tiles). Uppercase letters and digits are markers;
 * see FUTURE_MARKER_BASE.
 *
 * Legend:  . street   : sidewalk   = plaza   # neon building   g glass tower   _ lobby/depot floor
 *          - lab floor   d doorway   ~ canal   + bridge   p puddle (noisy)   , planter (hides you)
 *          x dark alley (hides you)   h billboard   v vending machine   k food stand   c tech crate
 *          s server rack   u lab bench   m station entrance   o statue/shrine base   b bench
 *          l street lamp   t tree   r railing
 */
export const FUTURE_MAP = [
  '################################################',
  '###########################gggggggggggggggggggg#',
  '##________c____c__cK#######g__________s-------g#',
  '##_____p_____pI_c___#######g_h________s--u-u--g#',
  '##_c_2___c__c_______#######g__________s---1---g#',
  '##_c___c_c_____cc___#######g___U______s-------g#',
  '##cp________________#######g__________ss-----sg#',
  '##_________c________#######g__________s-------g#',
  '##__c_____c_p____p__#######g__________ssss4sssg#',
  '##_G______________H_#######g_A________________g#',
  '##______c__c________##xx###g_____v____________g#',
  '##_______________c__##Ox###g,,,,________,,,__Bg#',
  'x#____c_______J_c6_p##xx###g__________________g#',
  'x#________________p_#xxx###g_C______________D_g#',
  'x##########dd########xxx###g__________________g#',
  'xx#########99#######xxxxxx#g__________________g#',
  'xx#########:X#######xxxxxx#ggggggggg3gggggggggg#',
  ':::::::::::::::::::::::::T::::::::::::::::::::::',
  '.........................p......p.5.Z.5.........',
  '..............v.............E...........pp..F...',
  '......p.........W.............h.................',
  '..L...h.p............Q..........8...........v...',
  '........p...pp..........R....p..................',
  '::::::::::::::::::::::::::::::::::::::::::::::::',
  'rrrrrrrrrr++rrrrrrrrrrrrrrrrrrrrrr++rrrrrrrrrrrr',
  '~~~~~~~~~~++~~~~~~~~~~~~~~~~~~~~~~++~~~~~~~~~~~~',
  '~~~~~~~~~~++~~~~~~~~~~~~~~~~~~~~~~++~~~~~~~~~~~~',
  'rrrrrrrrrr++rrrrrrrrrrrrrrrrrrrrrr++rrrrrrrrrrrr',
  '#::::::::::::::::::::::::::::::::::::::::::::::#',
  '#========,==p=,=,,==P=,t===t==,======,=========#',
  '#=t=====l===========k=======l=======,====ooo===#',
  '#=,===t======,==b====V====t======m=======ooo==t#',
  '#============p=====p=t=====,======,==t=========#',
  '#============b=t========7,,=Y,============0====#',
  '#=,===M========t============p=bt==,=,=t=====N=t#',
  '#==========t=,=================,t=====,=======,#',
  '#=====S===============t=========t===l==========#',
  '#========================t======,=====,=====p==#',
  '#,,===,======,===t=t================ttt========#',
  '################################################',
];

export const FUTURE_MARKER_BASE: Record<string, string> = {
  '0': '=',
  '1': '-',
  '2': '_',
  '3': '_',
  '4': '-',
  '5': '.',
  '6': '_',
  '7': 'o',
  '8': '.',
  '9': ':',
  A: '_',
  B: '_',
  C: '_',
  D: '_',
  E: '.',
  F: '.',
  G: '_',
  H: '_',
  I: '_',
  J: '_',
  K: '_',
  L: '.',
  M: '=',
  N: '=',
  O: 'x',
  P: '=',
  Q: 'p',
  R: '.',
  S: '=',
  T: 'c',
  U: 'c',
  V: '=',
  W: 'p',
  X: ':',
  Y: '=',
  Z: '.',
};
