/**
 * Middle Ages map: the Archbishop's castle near Cologne, 1248 (48x44 tiles). Uppercase letters and digits are markers;
 * see MEDIEVAL_MARKER_BASE for the tile underneath each one.
 *
 * Legend:  . grass   , bush (hides you)   : dirt road   = cobblestone   # castle wall
 *          _ stone floor   - wood floor   d doorway   h hole in a wall   r roof
 *          m house wall    n house door   ~ water     + bridge   t tree   c crate
 *          y hay   o forge   b barrel   s rack/shelf   u table   q well   p sealed door
 *          * flowers   [ stairs up inside the wall   > raised landing: hop down eastward only
 */
export const MEDIEVAL_MAP = [
  'tttttttttttttttttttttttttttttttttttttttttttttttt',
  '.tt.t.t.################################.......t',
  '.tttt.tt################################t......t',
  'tt.t..tt####ss_s_s_#-u-----u-#u4u##5#6##.......t',
  'tttt.t.t####s_3____#-------Y-#___#Q____##9...t.t',
  'tttttttt####s______d---------d___L_____[>Z...t.t',
  'tttttttt####s______#---------#___#____Q##9.....t',
  'ttt.tttt####s______#--b------#b_b###7#1#....t..t',
  't.tt.ttt#==#############N###############.......t',
  'ttttttt.#===============O==============#.......t',
  't.tttttt#=c=,,=F===,,,====,,c=,,=I=,,==#.t.....t',
  'ttttt.tt#=c=,,========y=======,,===,,,,#.......t',
  't.tttttt#==========================,,,,#,,,....t',
  '.t.ttttt#==A=========================C=#,,:::..t',
  'tttttttt#=,,==========================Uh.X,t:..t',
  'tttttttt#=,,=========,,,q=c=======,==,,#,,,t:.tt',
  'tttt.tt.#===cc==============,,,===,====#,,,t:..t',
  '.ttttt.t#=======,,,=========,,,==J==cc=#t...:..t',
  'ttttt.tt#yy====H,,,=cc==,,,===y==,,,,==#.tt.:..t',
  'tt.ttttt#y=,,,==========,,,====y=,,,,==#....:.tt',
  'tttt.tt.################G###############....:..t',
  'ttt.tt~~~~~~~~~~~~~~~~~+++~~~~~~~~~~~~~~....:..t',
  't.tt.t~~~~~~~~~~~~~~~~~+++~~~~~~~~~~~~~~....:.tt',
  '..............*t....t...:........t........t.:..t',
  '....t.t.....trrrrrr.....:....rrrrrrr........:..t',
  '.............rrrrrr.....:....rrrrrrr...*....:..t',
  '.....t.*.....rrrrrr.....:..*.rrrrrrr........:..t',
  '.........rrrrmmnmmm*....:...tmmmnmmm...*....:t.t',
  '.*.....*.rrrr..B*.bb....:.t..t...K.ob.......:..t',
  '..*..*.*.rrrr....tt.=========..*t....rrrr...:..t',
  '....*....mnmm.......=========........rrrr..t:..t',
  'tttttttttt..........==T======........rrrr...:..t',
  'tttttttttt..........====q====.....*..mnmm.*.:..t',
  'tttttttttt::::::::::=========:::::::::2::::::..t',
  'tt......*t:........*====V====.......D.........*t',
  'tt.......t:.*.......=========........tt........t',
  'tt...M...t:t..t..............t...t.t...........t',
  'tt......:::..t...t.t...........tt..t..rrrrrr...t',
  'tt..*....t.....t.t.t......t.......t...rrrrrr.W.t',
  'tt*..S...t.......tt.....t.....*.......rrrrrr...t',
  'tt....*..t.....t..........tt......t...mmn8mm...t',
  'tttttttttt...........t...t..t...*......Et......t',
  'tttttttttt.ttt..P.....tt..tt...................t',
  'tttttttttttttttttttttttttttttttttttttttttttttttt',
];

export const MEDIEVAL_MARKER_BASE: Record<string, string> = {
  '1': '%',
  '5': '%',
  '6': '%',
  '7': '%',
  P: '.',
  W: '.',
  '8': 'p',
  '9': '.',
  '2': ':',
  '3': '_',
  '4': '_',
  A: '=',
  B: '.',
  C: '=',
  D: '.',
  E: '.',
  F: '=',
  G: '=',
  H: '=',
  I: '=',
  J: '=',
  K: '.',
  L: 'd',
  M: '.',
  N: 'd',
  O: '=',
  Q: '_',
  S: '.',
  T: '=',
  U: '=',
  V: '=',
  X: ',',
  Y: '-',
  Z: '.',
};
