/**
 * Middle Ages map: the Archbishop's castle near Cologne, 1248 (48x62 tiles), with the Archbishop's
 * forest south of the village. Uppercase letters and digits are markers; see MEDIEVAL_MARKER_BASE
 * for the tile underneath each one.
 *
 * Legend:  . grass   , bush (hides you)   : dirt road   = cobblestone   # castle wall
 *          _ stone floor   - wood floor   d doorway   h hole in a wall   r roof
 *          m house wall    n house door   ~ water     + bridge   t tree   c crate
 *          y hay   o forge   b barrel   s rack/shelf   u table   q well   p sealed door
 *          * flowers   [ stairs up inside the wall   > raised landing: hop down eastward only
 *          f wattle fence   w stream   x dry brushwood (noisy)   k charcoal kiln   g mill wheel
 *          v blackberry brambles (low, can't be crossed)   z Pike's crypt floor (dark)
 */
export const MEDIEVAL_MAP = [
  'tttttttttttttttttttttttttttttttttttttttttttttttt',
  '.tt.t.t.################################.......t',
  '.tttt.tt################################t......t',
  'tt.t..tt####ss_s_s_#-u-----u-#u4u##5#6##.......t',
  'tttt.t.t####s_3____#-------Y-#___#_____##....t.t',
  'tttttttt####s______d---------d___d_____[>Z...t.t',
  'tttttttt####s______#---------#___#_____##......t',
  'ttt.tttt####s______#--b------#b_b###7#1#....t..t',
  't.tt.ttt#==#############N###############.......t',
  'ttttttt.#===============O==============#.......t',
  't.tttttt#=c=,,=F===,,,====,,c=,,=I=,,==#.t.....t',
  'ttttt.tt#=c=,,========y=======,,===,,,,#.......t',
  't.tttttt#==========================,,,,#,,,....t',
  '.t.ttttt#==A=========================C=#,,:::..t',
  'tttttttt#=,,===========================h.X,t:..t',
  'tttttttt#=,,=========,,,q=c=======,==,,#,,,t:.tt',
  'tttt.tt.#===cc==============,,,===,====#,,,t:..t',
  '.ttttt.t#=======,,,=========,,,==J==cc=#t...:..t',
  'ttttt.tt#yy====H,,,=cc==,,,===y==,,,,==#.tt.:..t',
  'tt.ttttt#y=,,,==========,,,====y=,,,,==#....:.tt',
  'tttt.tt.################G###############....:..t',
  'ttt.tt~~~~~~~~~~~~~~~~~+++~~~~~~~~~~~~~~....:..t',
  't.tt.t~~~~~~~~~~~~~~~~~+++~~~~~~~~~~~~~~....:.tt',
  '..............*t....t...:........t........t.:..t',
  '....t.t.....trrrrrr.....:....rrrrrrr........:..t',
  '.............rrrrrr.....:....rrrrrrr...*....:..t',
  '.....t.*.....rrrrrr.....:..*.rrrrrrr........:..t',
  '.........rrrrmmnmmm*....:...tmmmnmmm...*....:t.t',
  '.*.....*.rrrr..B*.bb....:.t..t...K.ob.......:..t',
  '..*..*.*.rrrr....tt.=========..*t....rrrr...:..t',
  '....*....mnmm.......=========........rrrr..t:..t',
  'tttttttttt..........==T======........rrrr...:..t',
  'tttttttttt..........====q====.....*.fmnmmff.:..t',
  'tttttttttt::::::::::=========::::::::::D::f::..t',
  'tt......*t:........*====V====.......fcbcb2f...*t',
  'tt.......t:.*.......=========.......fffffff....t',
  'tt...M...t:t..t.........:....t...t.t...........t',
  'tt......:::..t...t.t....:......tt..t..rrrrrr...t',
  'tt..*....t.....t.t.t....:.t.......t...mcQzcm...t',
  'tt*..S...t.......tt.....:.....*.......mzzzzm...t',
  'tt....*..t.....t........:.tt......t...mmn8pm...t',
  'tttttttttt...........t..:t..t...*......Et......t',
  'tttttttttt.ttt........tt:.tt...................t',
  'ttttttttttttttttttttttt,:,tttttttttttttttttttttt',
  'twwwwwwwwwwwwwwwwwwwwwww+wwwwwwwwwwwwwwwwwwwwwwt',
  'twwwwwwwwwwwwwwwwwwwwwww+wwwwwwwwwwwwwwwwwwwwwwt',
  'tttttttttttttttttt,,.,..L.*.,,ttttttttttttttwwwt',
  'ttttttttt,,ttttt,t,...,.:..,,t,tttt,,tttttttwwwt',
  'ttttttttt,,tttttt,..t..,:...,tttttt,,tttttttwwwt',
  'tttttt:R:::::::::::::::::::::::::::::::::0ttwwwt',
  'tttt,.:.vvvv,,vvvv,,vvvvvvvvvv,,vvvvvvvv:xxtwwwt',
  'tt,,,.:.vvvv,,vvvv,,vvvvvvvvvv,,vvvvvvvv:xxtwwwt',
  'tt,,..::...tttttttttttttttttttttt::::::::xxtwwwt',
  'tt,,...:..k.ttttttttttttttttttttt:tt9ttxxxxtwwwt',
  'ttxx..U..x..ttttttttttttttttttttt::::::xxrrrrwwt',
  'tt,,....x...tttttttttttttttttttvvvvvvv:xxrrrrwwt',
  'tt,W.x.....xtttttttttttttttttttttt......:rrrrwwt',
  'tt,,,,....tttttttttttttttttttttttt..*...:nmmmwwt',
  'tttttttttttttttttttttttttttttttttt...P....wgwwwt',
  'tttttttttttttttttttttttttttttttttt*....*..wwwwwt',
  'tttttttttttttttttttttttttttttttttt..*..t..wwwwwt',
  'tttttttttttttttttttttttttttttttttttttttttttttttt',
];

export const MEDIEVAL_MARKER_BASE: Record<string, string> = {
  '1': '%',
  '5': '%',
  '6': '%',
  '7': '%',
  P: '.',
  R: ':',
  W: '.',
  '0': ':',
  '8': 'd',
  '9': '.',
  '2': '.',
  '3': '_',
  '4': '_',
  A: '=',
  B: '.',
  C: '=',
  D: ':',
  E: '.',
  F: '=',
  G: '=',
  H: '=',
  I: '=',
  J: '=',
  K: '.',
  L: ':',
  M: '.',
  N: 'd',
  O: '=',
  Q: 'z',
  S: '.',
  T: '=',
  U: '.',
  V: '=',
  X: ',',
  Y: '-',
  Z: '.',
};
