/**
 * The Long Drought map, 2240: dry gardens in Madrid, the empty bed of the
 * Manzanares, a ruined Metro entrance and the Museo Nacional de Ciencias
 * Naturales (44x54 tiles), with the abandoned Metro station below the city. Uppercase letters and digits are markers; see
 * RUINS_MARKER_BASE.
 *
 * Legend:  . dust   , dry scrub (hides you)   : cracked road   s dune / dry riverbed   # ruined wall
 *          t dead tree   r debris   q big rubble   = marble   w museum wall   c column   _ lab floor
 *          d doorway   v car wreck   k showcase   g dry fountain   l dead street lamp
 *          b Pike's cot   h books and papers   a door panel (in the lab wall)   y smashed showcase   i litter   x broken showcase glass (dark, crunches)   m mineral hall floor (dark)   n console   e Metro stairs   p platform (dark)   j tracks (dark)
 *          z drifted sand (dark)   o tunnel wall (low)   f campfire   u cistern
 */
export const RUINS_MAP = [
  '############################################',
  '#s.s...s.....s..s..,s................,.s...#',
  '#s......wwwwwwwwwwwwwwwwwwwwwwwwwwww......,#',
  '#....,..wss==qq===========wwh___3bww....s.s#',
  '#..,.,..ws===========r===sww_X_P_bwws..,.,,#',
  '#s......w==1=====y=====1==wwh_____ww.s..s..#',
  '#..,..,.w====r=====i====i=wwwNDwwwwwwwwwwww#',
  '#.s.....w=1=========y=====wZ====q==wmmmmmmw#',
  '#,..s...w===G==r========1=wr=r=====w9x0mm9w#',
  '#.s.....w==i=====B========w======r=wmmxmxmw#',
  '#.......w=1========r==i===J========wxmmmxmw#',
  '#.......w=====y===========w======r8w9mxmmmw#',
  '#ss....sw==1=======y===6==w=q=r=r==7mmxmxxw#',
  '#.......w====i==i=====r===w==T=====wmxmmm9w#',
  '#...,ss.w=====O=====H===1=w========w9mxmxmw#',
  '#....s..wq==r===qq===R====wrr======wmmmmxmw#',
  '#...,...w=========sss=====w=====r=Zwwwwwwww#',
  '#..,....wwwwwwwwwwwwwKwwwwwwwwwwwwww...s.s.#',
  '#....s.,,=c==c==c==c====c==c==c==c=.....s..#',
  '#......,.s....,....,:::s.,.....,..,s.,.s...#',
  '#......,...r.t.t,...:::..,t.st..#...t.#....#',
  '#..s.s...s.#E.g...s.:::#...sg...F....t.....#',
  '#...,t...ss#s,.,tl..:::.sl..#..............#',
  '#..t,r.r...s.r....s.Q::,r........s,....t..s#',
  '#:::::::v:::::::::::::::::::::::::::::v::::#',
  '#:::::::::::::::::::::::::::::v::::::::::::#',
  '#sssr...t...s.#.,...s..st......s.s......,.t#',
  '#ssAst.,s....t.,#.,.s........s...s,.....C..#',
  '#rssWr.,....t,....r...................,.#.s#',
  '#ssss.#s.,....s,s,t...........t.#..s...,,..#',
  '#sqssl...........s....gg.......,t.##.r.tst.#',
  '#rsss,s.........ttt...gg......,..,.,,.t..t.#',
  '#rsss......M....s.,.........s.s,..s,,..s.#.#',
  '#ssssr.r........,.t............s,..s.s.t...#',
  '#ssqs......S............................,t.#',
  '#ssss..t.....................s,..t.,,r,..,.#',
  '#rsss.#...,.,,..,......,.s...ss#....s....,.#',
  '#sssstt.t,.....s....s.s,...,.Vee,..........#',
  '#rsssr,rs...,rt.,srt,st.s,s.s.ee,.s........#',
  '##############################ee############',
  'ooooooooooooooooooooooooooooooeeoooooooooooo',
  'oooooooooooooopppppppppppppppp2pppppppppppoo',
  'ooooooooooooooppppopppppopppppppppppopppppoo',
  'ooooooooooooooppppppppppppppppppppppppppppoo',
  'oojjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjzjjjjjjjjjo',
  'ooIjjjjjjjjjjjjjjjjjzjjjjjjjjjjjjjjjjjjjjjLo',
  'oojjjjjjjjjjjjjjjjjjjjjjjjjzjjjjjjjjjjjjjjjo',
  'oozzpppppppzzooooooooooooooooooooooooooooooo',
  'oozuzzzzYzzzzooooooooooooooooooooooooooooooo',
  'oozUzzfzzzzzzooooooooooooooooooooooooooooooo',
  'oozzzzzzzzzzzooooooooooooooooooooooooooooooo',
  'oozzzzzzzzzzzooooooooooooooooooooooooooooooo',
  'oooooooooooooooooooooooooooooooooooooooooooo',
  'oooooooooooooooooooooooooooooooooooooooooooo',
];

export const RUINS_MARKER_BASE: Record<string, string> = {
  '0': 'm',
  '1': 'k',
  '2': 'p',
  '3': 'h',
  '6': 'k',
  '7': 'd',
  '8': 'n',
  '9': 'k',
  A: 's',
  B: '=',
  C: '.',
  D: 'd',
  E: '.',
  F: '.',
  G: '=',
  H: '=',
  I: 'j',
  J: '=',
  K: '=',
  L: 'j',
  M: '.',
  N: 'a',
  O: '=',
  P: '_',
  Q: ':',
  R: '=',
  S: '.',
  T: '=',
  U: 'u',
  V: '.',
  W: 's',
  X: '_',
  Y: 'z',
  Z: 'r',
};
