/**
 * The Long Drought map, 2240: dry gardens in Madrid, the empty bed of the
 * Manzanares, a ruined Metro entrance and the Museo Nacional de Ciencias
 * Naturales (44x40 tiles). Uppercase letters and digits are markers; see
 * RUINS_MARKER_BASE.
 *
 * Legend:  . dust   , dry scrub (hides you)   : cracked road   s dune / dry riverbed   # ruined wall
 *          t dead tree   r debris   q big rubble   = marble   w museum wall   c column   _ lab floor
 *          d doorway   v car wreck   k showcase   g dry fountain   l dead street lamp
 */
export const RUINS_MAP = [
  '############################################',
  '#s.s...s.....s..s..,s................,.s...#',
  '#s......wwwwwwwwwwwwwwwwwwwwwwwwwwww......,#',
  '#....,..w=================ww______ww....s.s#',
  '#..,.,..w=================ww_X_P__wws..,.,,#',
  '#s......w==3===========4==ww______ww.s..s..#',
  '#..,..,.w=================wwwwDwwwww..s....#',
  '#.s.....w=================wZ=N==q==ws.s.s..#',
  '#,..s...w===G=============wr=r=====ws...,..#',
  '#.s.....w========B========w======r=w,......#',
  '#.......w=================J========w..,...s#',
  '#.......w=================w======r=w.......#',
  '#ss....sw==5===========6==w=q=r=r==w..,....#',
  '#.......w=================w==T=====w......s#',
  '#...,ss.w=====O=====H=====w========w.......#',
  '#....s..w============R====wrr======w....,..#',
  '#...,...w=================w=====r=Zw.......#',
  '#..,....wwwwwwwwwwwwwKwwwwwwwwwwwwww...s.s.#',
  '#....s.,,=c==c==c==c====c==c==c==c=.....s..#',
  '#......,.s....,....,:::s.,.....,..,s.,.s...#',
  '#......,...r.t.t,...:::..,t.st..#...t.#....#',
  '#..s.s...s.#E.g...s.:::#...sg...F....t.....#',
  '#...,t...ss#s,.,tl..:::.sl..#..............#',
  '#..t,r.r...s.r....s.Q::,r........s,....t..s#',
  '#:::::::v:::::::::::::::::::::::::::::v::::#',
  '#:::::::::::::::::::::::::::::v::::::::::::#',
  '#sssr...t...s.#.,...s..st......s.s......,.t#',
  '#ssAst.,s....t.,#.,.s........s...s,.....C..#',
  '#rssWr.,....t,....r...................,.#.s#',
  '#ssss.#s.,....s,s,t...........t.#..s...,,..#',
  '#sqssl...........s....gg.......,t.V#.r.tst.#',
  '#rsss,s.........ttt...gg.Y....,..,.,,.t..t.#',
  '#rsss......M....s.,.........s.s,..s,,..s.#.#',
  '#ssssr.r........,.t............s,..s.s.t...#',
  '#ssqs......S....I.....................L.,t.#',
  '#ssss..t.....................s,..t.,,r,..,.#',
  '#rsss.#...,.,,..,......,.s...ss#....s....,.#',
  '#sssstt.t,.....s....s.s,...,.s..,..........#',
  '#rsssr,rs...,rt.,srt,st.s,s.s...,.s........#',
  '############################################',
];

export const RUINS_MARKER_BASE: Record<string, string> = {
  '3': 'k',
  '4': 'k',
  '5': 'k',
  '6': 'k',
  A: 's',
  B: '=',
  C: '.',
  D: 'd',
  E: '.',
  F: '.',
  G: '=',
  H: '=',
  I: '.',
  J: '=',
  K: '=',
  L: '.',
  M: '.',
  N: '=',
  O: '=',
  P: '_',
  Q: ':',
  R: '=',
  S: '.',
  T: '=',
  V: '#',
  W: 's',
  X: '_',
  Y: '.',
  Z: 'r',
};
